In [247]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [248]:
df = pd.read_csv('datasets.csv') 
df1=df

In [249]:
df.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,wbcc,rbcc,htn,dm,cad,appet,pe,ane,rac,class
0,23,80,1.025,0,0,normal,normal,notpresent,notpresent,111,...,7200,5,no,no,no,good,no,no,2,notckd
1,30,70,1.015,0,0,?,normal,notpresent,notpresent,101,...,?,?,no,no,no,poor,no,no,2,ckd
2,59,70,1.01,1,3,abnormal,abnormal,notpresent,notpresent,424,...,10200,4.1,yes,yes,yes,good,no,no,0,ckd
3,45,80,1.025,0,0,normal,normal,notpresent,notpresent,82,...,9100,4.7,no,no,no,good,no,no,2,notckd
4,22,60,1.025,0,0,normal,normal,notpresent,notpresent,97,...,7900,6.4,no,no,no,good,no,no,2,notckd

In [250]:
df.shape

(350, 26)

In [251]:
import pandas as pd
import numpy as np
import re

# Function to count special characters in one value
def count_special_chars(val):
    if pd.isna(val):
        return 0
    return len(re.findall(r'[^A-Za-z0-9\s._-]', str(val)))

# Count total special characters per column
special_char_counts = df.applymap(count_special_chars).sum().sort_values(ascending=False)

# Show columns with most special characters
print("🔍 Special character counts per column:")
print(special_char_counts[special_char_counts > 0])

🔍 Special character counts per column:
rbc      134
rbcc     112
wbcc      91
pot       80
sod       79
pcv       63
pc        52
hemo      47
bgr       40
su        39
sg        38
al        37
bu        17
sc        17
bp        11
age        7
ba         4
pcc        4
appet      1
pe         1
ane        1
dtype: int64

C:\Users\Admin\AppData\Local\Temp\ipykernel_20848\3229514971.py:12: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  special_char_counts = df.applymap(count_special_chars).sum().sort_values(ascending=False)

In [254]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 26 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     343 non-null    object
 1   bp      339 non-null    object
 2   sg      312 non-null    object
 3   al      313 non-null    object
 4   su      311 non-null    object
 5   rbc     216 non-null    object
 6   pc      298 non-null    object
 7   pcc     346 non-null    object
 8   ba      346 non-null    object
 9   bgr     310 non-null    object
 10  bu      333 non-null    object
 11  sc      333 non-null    object
 12  sod     271 non-null    object
 13  pot     270 non-null    object
 14  hemo    303 non-null    object
 15  pcv     288 non-null    object
 16  wbcc    260 non-null    object
 17  rbcc    239 non-null    object
 18  htn     350 non-null    object
 19  dm      350 non-null    object
 20  cad     350 non-null    object
 21  appet   349 non-null    object
 22  pe      349 non-null    object
 23  ane     349 non-null    object
 24  rac     350 non-null    int64
 25  class   350 non-null    object
dtypes: int64(1), object(25)
memory usage: 71.2+ KB

In [255]:
df.replace('?', np.nan, inplace=True)

In [273]:
cat_cols = ['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'class']
num_cols = [
    'age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc',
    'sod', 'pot', 'hemo', 'pcv', 'wbcc', 'rbcc', 'rac'
]

In [274]:
df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')

In [275]:
for col in num_cols:
    if df[col].notna().sum() > 0:  # if at least one valid value
        df[col] = df[col].fillna(df[col].mean())
    else:
        df[col] = 0

In [276]:
for col in cat_cols:
    if df[col].isna().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

In [260]:
print(df.isna().sum())

age      0
bp       0
sg       0
al       0
su       0
rbc      0
pc       0
pcc      0
ba       0
bgr      0
bu       0
sc       0
sod      0
pot      0
hemo     0
pcv      0
wbcc     0
rbcc     0
htn      0
dm       0
cad      0
appet    0
pe       0
ane      0
rac      0
class    0
dtype: int64

In [277]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 26 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     350 non-null    float64
 1   bp      350 non-null    float64
 2   sg      350 non-null    float64
 3   al      350 non-null    float64
 4   su      350 non-null    float64
 5   rbc     350 non-null    object
 6   pc      350 non-null    object
 7   pcc     350 non-null    object
 8   ba      350 non-null    object
 9   bgr     350 non-null    float64
 10  bu      350 non-null    float64
 11  sc      350 non-null    float64
 12  sod     350 non-null    float64
 13  pot     350 non-null    float64
 14  hemo    350 non-null    float64
 15  pcv     350 non-null    float64
 16  wbcc    350 non-null    float64
 17  rbcc    350 non-null    float64
 18  htn     350 non-null    object
 19  dm      350 non-null    object
 20  cad     350 non-null    object
 21  appet   350 non-null    object
 22  pe      350 non-null    object
 23  ane     350 non-null    object
 24  rac     350 non-null    int64
 25  class   350 non-null    object
dtypes: float64(14), int64(1), object(11)
memory usage: 71.2+ KB

In [244]:
df.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,wbcc,rbcc,htn,dm,cad,appet,pe,ane,rac,class
0,23.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,111.0,...,7200.00000,5.000000,no,no,no,good,no,no,2,notckd
1,30.0,70.0,1.015,0.0,0.0,normal,normal,notpresent,notpresent,101.0,...,8370.27027,4.713866,no,no,no,poor,no,no,2,ckd
2,59.0,70.0,1.010,1.0,3.0,abnormal,abnormal,notpresent,notpresent,424.0,...,10200.00000,4.100000,yes,yes,yes,good,no,no,0,ckd
3,45.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,82.0,...,9100.00000,4.700000,no,no,no,good,no,no,2,notckd
4,22.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,97.0,...,7900.00000,6.400000,no,no,no,good,no,no,2,notckd

In [246]:
target_col = 'class'
X = df.drop(columns=[target_col])
y = df[target_col]

In [213]:
drop_cols = ['rac', 'hemo', 'sg', 'pcv', 'rbcc', 'al']

In [214]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [215]:
ordinal_cols = ['rbc', 'pc', 'appet']

In [216]:
nominal_cols = ['pcc', 'ba', 'htn', 'dm', 'cad', 'pe', 'ane']

In [217]:
ordinal_mapping = [
    ['abnormal', 'normal'],   
    ['abnormal', 'normal'],  
    ['poor', 'good']         
]

In [218]:
df['class_encoded'] = df['class'].map({'ckd': 1, 'notckd': 0})

In [219]:
corr_with_target = df[num_cols].corrwith(df['class_encoded']).sort_values(ascending=False)
print("🔗 Correlation of Numeric Features with Target (class):")
print(corr_with_target)

🔗 Correlation of Numeric Features with Target (class):
al      0.532129
bgr     0.381870
bu      0.359550
bp      0.329387
su      0.305614
sc      0.279266
age     0.241626
wbcc    0.180821
pot     0.064282
sod    -0.324291
rbcc   -0.551479
pcv    -0.655727
sg     -0.666296
hemo   -0.718252
rac    -0.794406
dtype: float64

In [261]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [262]:

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

In [263]:
ordinal_transformer = Pipeline(steps=[
    ('ordinal', OrdinalEncoder(categories=ordinal_mapping))
])

In [264]:
nominal_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

In [265]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, num_cols),
        ('ord', ordinal_transformer, ordinal_cols),
        ('nom', nominal_transformer, nominal_cols)
    ]
)

In [266]:
from sklearn.linear_model import LogisticRegression

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(
        penalty='l2',       # L2 = Ridge regularization
        C=0.3,              # Lower C = stronger regularization
        solver='lbfgs',
        max_iter=2000,
        class_weight='balanced',
        random_state=42
    ))
])

In [267]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'bp', 'sg', 'al',
                                                   'su', 'bgr', 'bu', 'sc',
                                                   'sod', 'pot', 'hemo', 'pcv',
                                                   'wbcc', 'rbcc', 'rac']),
                                                 ('ord',
                                                  Pipeline(steps=[('ordinal',
                                                                   OrdinalEncoder(categories=[['abnormal',
                                                                                               'normal'],
                                                                                              ['abnormal',
                                                                                               'normal'],
                                                                                              ['poor',
                                                                                               'good']]))]),
                                                  ['rbc', 'pc', 'appet']),
                                                 ('nom',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['pcc', 'ba', 'htn', 'dm',
                                                   'cad', 'pe', 'ane'])])),
                ('classifier',
                 LogisticRegression(C=0.3, class_weight='balanced',
                                    max_iter=2000, random_state=42))])

In [268]:
y_pred = model.predict(X_test)

In [269]:
for col in X.columns:
    corr = pd.factorize(df[target_col])[0]
    try:
        c = np.corrcoef(pd.to_numeric(df[col], errors='coerce'), corr)[0, 1]
        if abs(c) > 0.95:
            print(f"⚠️ {col} correlates too strongly with target: {c:.3f}")
    except:
        pass

In [270]:
print(y.value_counts(normalize=True))

class
ckd       0.625714
notckd    0.374286
Name: proportion, dtype: float64

In [271]:
print("✅ Model Accuracy:", round(accuracy_score(y_test, y_pred) * 100, 2), "%")
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

✅ Model Accuracy: 100.0 %

Classification Report:
               precision    recall  f1-score   support

         ckd       1.00      1.00      1.00        44
      notckd       1.00      1.00      1.00        26

    accuracy                           1.00        70
   macro avg       1.00      1.00      1.00        70
weighted avg       1.00      1.00      1.00        70


Confusion Matrix:
 [[44  0]
 [ 0 26]]

In [272]:
from sklearn.model_selection import cross_val_score

# Your model pipeline is already defined, which is perfect
# Now, let's evaluate it using 5-fold cross-validation
# This runs the entire process (preprocessing + training) 5 times
scores = cross_val_score(model, X, y, cv=5, scoring='accuracy')

# Print the results
print("--- Cross-Validation Results ---")
print(f"Individual fold scores: {scores}")
print(f"Average accuracy: {scores.mean():.4f} (+/- {scores.std() * 2:.4f})")

--- Cross-Validation Results ---
Individual fold scores: [0.98571429 1.         1.         1.         0.95714286]
Average accuracy: 0.9886 (+/- 0.0333)

In [230]:
print("✅ Model Accuracy:", round(accuracy_score(y_test, y_pred) * 100, 2), "%")
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

✅ Model Accuracy: 100.0 %

Classification Report:
               precision    recall  f1-score   support

         ckd       1.00      1.00      1.00        44
      notckd       1.00      1.00      1.00        26

    accuracy                           1.00        70
   macro avg       1.00      1.00      1.00        70
weighted avg       1.00      1.00      1.00        70


Confusion Matrix:
 [[44  0]
 [ 0 26]]